import{i as a,S as h}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const m="46878404-43e11e495eedf0f56c253a7d9",g="https://pixabay.com/api/";function y(i){const o=Math.floor(Math.random()*10)+1,r=new URLSearchParams({key:m,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}),n=`${g}?${r.toString()}`;return fetch(n).then(e=>{if(!e.ok)throw new Error("...UPS");return e.json()}).then(e=>e.hits.length===0?(a.error({title:"Error",message:"Sorry, no images were found for your request. Try again!",position:"topCenter",backgroundColor:"#ef4040"}),[]):e.hits).catch(e=>{console.log(e),a.error({title:"Error",message:"An error occurred while receiving data. Try again.",position:"topCenter",backgroundColor:"#ef4040"})})}const l=document.querySelector(".list");function b(i){const o=i.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:s,comments:d,downloads:p})=>`
        <div class="gallery-item">
            <a href="${n}">
                <img src="${r}" alt="${e}" width="360" height="200"/>
            </a>
            <div class="info">
                <p class="info-text"><b class="xz">Likes:</b> ${t}</p>
                <p class="info-text"><b class="xz">Views:</b> ${s}</p>
                <p class="info-text"><b class="xz">Comments:</b> ${d}</p>
                <p class="info-text"><b class="xz">Downloads:</b> ${p}</p>
            </div>
        </div>
    `).join("");l.innerHTML="",l.insertAdjacentHTML("beforeend",o)}const u=document.querySelector(".search-form"),L=document.querySelector(".search-form input"),f=document.querySelector(".loader");let c;u.addEventListener("submit",w);function w(i){i.preventDefault();const o=L.value.trim();if(o==="")return a.info({position:"topRight",title:"Error",message:"Fill in the request field"});x(),y(o).then(r=>{r&&r.length>0&&(b(r),c?c.refresh():c=new h(".gallery-item a",{captionsData:"alt",captionDelay:250}))}).catch(r=>{console.log(r),a.error({position:"topRight",title:"Error",message:"An error occurred while retrieving images. Try again!",backgroundColor:"#ef4040"})}).finally(()=>{v(),u.reset()})}function x(){f.style.display="block"}function v(){f.style.display="none"}
//# sourceMappingURL=index.js.map
