import{i as a,S as p}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const m="46878404-43e11e495eedf0f56c253a7d9",h="https://pixabay.com/api/";function g(t){if(!t||t.trim()==="")return a.error({title:"Ошибка",message:"Введите запрос.",position:"topCenter",backgroundColor:"#ef4040"}),Promise.resolve([]);const o=Math.floor(Math.random()*10)+1,n=new URLSearchParams({key:m,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}),i=`${h}?${n.toString()}`;return fetch(i).then(e=>{if(!e.ok)throw new Error("Ошибка при получении данных от API");return e.json()}).then(e=>e.hits.length===0?(a.error({title:"Ошибка",message:"Извините, изображения не найдены по вашему запросу. Попробуйте снова!",position:"topCenter",backgroundColor:"#ef4040"}),[]):e.hits).catch(e=>(console.error(e),a.error({title:"Ошибка",message:"Произошла ошибка при получении данных. Попробуйте снова.",position:"topCenter",backgroundColor:"#ef4040"}),[]))}const u=document.querySelector(".list");function y(t){if(!t||t.length===0){u.innerHTML="<p>No images found.</p>";return}const o=t.map(({webformatURL:n,largeImageURL:i,tags:e,likes:r,views:s,comments:c,downloads:f})=>`  
        <div class="gallery-item">  
            <a href="${i}" target="_blank" rel="noopener noreferrer">  
                <img src="${n}" alt="${e||"Image"}" width="360" height="200" loading="lazy"/>  
            </a>  
            <div class="info">  
                <p class="info-text"><b class="xz">Likes:</b> ${r}</p>  
                <p class="info-text"><b class="xz">Views:</b> ${s}</p>  
                <p class="info-text"><b class="xz">Comments:</b> ${c}</p>  
                <p class="info-text"><b class="xz">Downloads:</b> ${f}</p>  
            </div>  
        </div>  
    `).join("");u.innerHTML="",u.insertAdjacentHTML("beforeend",o)}document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".search-form"),o=document.querySelector(".search-form input"),n=document.querySelector(".loader"),i=document.querySelector(".gallery");let e;if(!t||!o||!n||!i){console.error("Не удалось найти один или несколько элементов в DOM.");return}t.addEventListener("submit",r);function r(f){f.preventDefault();const d=o.value.trim();if(d===""){a.info({title:"Error",message:"Fill in the request field"});return}s(),g(d).then(l=>{Array.isArray(l)&&l.length>0?(y(l),e?e.refresh():e=new p(".gallery-item a",{captionsData:"alt",captionDelay:250})):a.warning({title:"No Results",message:"No images found. Try a different search."})}).catch(l=>{console.error("Ошибка при загрузке данных:",l),a.error({position:"topRight",title:"Error",message:"An error occurred while retrieving images. Try again!",backgroundColor:"#ef4040"})}).finally(()=>{c(),t.reset()})}function s(){n.style.display="block"}function c(){n.style.display="none"}});
//# sourceMappingURL=index.js.map
